# GoReleaser config for lib1
version: 2
project_name: lib1

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: lib1-cli
    main: ./cmd/main.go
    binary: lib1-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: default
    formats: [tar.gz]
    files:
      - README.md
      - LICENSE*
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"
