style: github
template: .chglog/CHANGELOG.tpl.md
info:
  title: "Changelog"
  repository_url: "https://github.com/your-org/your-repo"
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
  commit_groups:
    title_maps:
      feat: "Features"
      fix: "Bug Fixes"