# GoReleaser configuration for mono-repo-release
# Documentation: https://goreleaser.com

version: 2

project_name: mono-repo-release:lib2

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy
    # Run tests before building
    - go test ./...

builds:
  # Lib2 CLI tool
  - id: lib2-cli
    main: ./pkg/lib2/cmd
    binary: lib2-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: default
    formats: [tar.gz]
    files:
      - README.md
      - LICENSE*
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .ProjectName }}"
  draft: false
  prerelease: auto
  mode: append
  ids:
    - lib2
  name_template: "{{.ProjectName}} {{.Tag}}"
  header: |
    ## What's new in {{ .ProjectName }} v{{ .Version }}

    Welcome to this new release!
  footer: |
    ## Docker Images

    Docker images are available at:
    - `ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Version }}`
    - `ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:latest`

    **Full Changelog**: https://git.i.mercedes-benz.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}/compare/{{ .PreviousTag }}...{{ .Tag }}
