#!/bin/bash
set -euo pipefail

VERSION=$1

# Update all version.go files
find packages -name 'version.go' | while read file; do
  PKG=$(dirname "$file" | xargs basename)
  cat > "$file" <<EOF
package $PKG

// Code generated by release tool. DO NOT EDIT.

const Version = "$VERSION"
EOF
done

# Update Bazel dependencies if needed
sed -i.bak "s/version = \".*\"/version = \"$VERSION\"/" WORKSPACE
rm WORKSPACE.bak